# based on https://medium.com/dev-genius/continuous-deployment-for-mkdocs-with-github-actions-7dceec87f0ea
name: Build Documentation
on: 
  push: 
    branches: [development]

jobs: 
  build: 
    name: Build and Deploy Documentation 
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout Repository 
        uses: actions/checkout@v2
      - name: Set up Python 3
        uses: actions/setup-python@v2 
        with: 
          python-version: '3.x'
      - name: Install dependencies 
        run: | 
          python -m pip install --upgrade pip 
          pip install mkdocs-material 
      - name: Deploy 
        run: |
          cd documentation
          mkdocs gh-deploy
